/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Identity */
        post: operations["create_identity_api_identity_post"];
        delete?: never;
        options?: never;
        head?: never;
        /** Update Identity */
        patch: operations["update_identity_api_identity_patch"];
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devices */
        get: operations["devices_api_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Device */
        delete: operations["revoke_device_api_devices__device_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Pairing */
        post: operations["create_pairing_api_pairings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairings/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Pairing */
        post: operations["request_pairing_api_pairings_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairings/{pairing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pairing Status */
        get: operations["pairing_status_api_pairings__pairing_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairings/{pairing_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Pairing */
        post: operations["confirm_pairing_api_pairings__pairing_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairings/{pairing_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Pairing */
        post: operations["complete_pairing_api_pairings__pairing_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lookup Recipes */
        post: operations["lookup_recipes_api_recipes_lookup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recipes */
        get: operations["list_recipes_api_recipes_get"];
        put?: never;
        /** Create Recipe */
        post: operations["create_recipe_api_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_api_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["get_recipe_api_recipes__recipe_id__get"];
        /** Update Recipe */
        put: operations["update_recipe_api_recipes__recipe_id__put"];
        post?: never;
        /** Delete Recipe */
        delete: operations["delete_recipe_api_recipes__recipe_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Recipe View */
        post: operations["create_recipe_view_api_recipes__recipe_id__views_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredients/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Lines */
        post: operations["parse_lines_api_ingredients_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse */
        post: operations["parse_api_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enrich Recipe */
        post: operations["enrich_recipe_api_recipes__recipe_id__enrich_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users */
        get: operations["users_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/admin/recipes/{recipe_id}/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Owner */
        post: operations["assign_owner_api_admin_recipes__recipe_id__owner_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/recipes/{recipe_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revisions */
        get: operations["revisions_api_admin_recipes__recipe_id__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/recipes/{recipe_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore */
        post: operations["restore_api_admin_recipes__recipe_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/merge/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Merge Preview */
        get: operations["merge_preview_api_admin_merge_preview_get"];
        put?: never;
        /** Merge Preview Body */
        post: operations["merge_preview_body_api_admin_merge_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge */
        post: operations["merge_api_admin_merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Events */
        get: operations["audit_events_api_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Photos */
        get: operations["photos_api_admin_photos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/photos/{photo_id}/moderate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Moderate Photo */
        post: operations["moderate_photo_api_admin_photos__photo_id__moderate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Moderate Photo */
        post: operations["moderate_photo_api_admin_photos__photo_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/site-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_site_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/site-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Settings */
        put: operations["update_settings_api_admin_site_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Photos */
        get: operations["photos_api_photos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Photo */
        post: operations["upload_photo_api_recipes__recipe_id__photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{photo_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Photo Image */
        get: operations["photo_image_api_photos__photo_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Photo */
        delete: operations["delete_photo_api_photos__photo_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminUser */
        AdminUser: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** State */
            state: string;
            /** Trusted */
            trusted: boolean;
            /** Merged Into */
            merged_into?: string | null;
            /** Last Login At */
            last_login_at?: string | null;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
            /** Merged User Ids */
            merged_user_ids?: string[];
        };
        /** AdminUsersResponse */
        AdminUsersResponse: {
            /** Users */
            users: components["schemas"]["AdminUser"][];
            /** Items */
            items: components["schemas"]["AdminUser"][];
            /** Total */
            total: number;
            /** Start */
            start: number;
            /** Limit */
            limit: number;
            /** Has More */
            has_more: boolean;
        };
        /** Body_upload_photo_api_recipes__recipe_id__photos_post */
        Body_upload_photo_api_recipes__recipe_id__photos_post: {
            /** File */
            file: string;
            /**
             * Caption
             * @default
             */
            caption: string;
        };
        /** CompleteInput */
        CompleteInput: {
            /**
             * Switch Profile
             * @constant
             */
            switch_profile: true;
        };
        /** GramEstimate */
        GramEstimate: {
            /** Amount */
            amount?: number | string | null;
            /** Low */
            low?: number | null;
            /** High */
            high?: number | null;
            /**
             * Estimated
             * @default true
             */
            estimated: boolean;
            /**
             * Basis
             * @default
             */
            basis: string;
            /** Refusal Reason */
            refusal_reason?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Ingredient */
        Ingredient: {
            /** Id */
            id?: string;
            /**
             * Original Text
             * @default
             */
            original_text: string;
            /** Quantity */
            quantity?: string | null;
            /** Quantity Max */
            quantity_max?: string | null;
            /**
             * Unit
             * @default
             */
            unit: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Preparation
             * @default
             */
            preparation: string;
            /**
             * Optional
             * @default false
             */
            optional: boolean;
            /** Grams */
            grams?: null;
        };
        /** IngredientGroup */
        IngredientGroup: {
            /** Id */
            id?: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Ingredients */
            ingredients?: components["schemas"]["Ingredient"][];
        };
        /** IngredientGroupOutput */
        IngredientGroupOutput: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Ingredients */
            ingredients: components["schemas"]["IngredientOutput"][];
        };
        /** IngredientLineInput */
        IngredientLineInput: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** IngredientLineResult */
        IngredientLineResult: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /**
             * Method
             * @constant
             */
            method: "llm";
            ingredient: components["schemas"]["IngredientOutput"];
        };
        /** IngredientLinesRequest */
        IngredientLinesRequest: {
            /** Lines */
            lines: components["schemas"]["IngredientLineInput"][];
        };
        /** IngredientLinesResult */
        IngredientLinesResult: {
            /** Items */
            items: components["schemas"]["IngredientLineResult"][];
        };
        /** IngredientOutput */
        IngredientOutput: {
            /** Id */
            id: string;
            /** Original Text */
            original_text: string;
            /** Quantity */
            quantity?: string | null;
            /** Quantity Max */
            quantity_max?: string | null;
            /**
             * Unit
             * @default
             */
            unit: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Preparation
             * @default
             */
            preparation: string;
            /**
             * Optional
             * @default false
             */
            optional: boolean;
            grams?: components["schemas"]["GramEstimate"] | null;
        };
        /** MergeInput */
        MergeInput: {
            /** Source Id */
            source_id: string;
            /** Target Id */
            target_id: string;
            /**
             * Confirm
             * @constant
             */
            confirm: true;
        };
        /** MergePreviewInput */
        MergePreviewInput: {
            /** Source Id */
            source_id: string;
            /** Target Id */
            target_id: string;
        };
        /** ModerationInput */
        ModerationInput: {
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "approved" | "rejected";
        };
        /** OwnerInput */
        OwnerInput: {
            /** Owner Id */
            owner_id: string | null;
            /** Expected Revision */
            expected_revision: number;
        };
        /** OwnerResult */
        OwnerResult: {
            /** Id */
            id: string;
            /** Owner Id */
            owner_id: string | null;
            /** Author Name */
            author_name: string | null;
            /** Revision */
            revision: number;
        };
        /** PairingInput */
        PairingInput: {
            /** Code */
            code?: string | null;
            /** Token */
            token?: string | null;
        };
        /** ParseRequest */
        ParseRequest: {
            /** Source Text */
            source_text: string;
        };
        /** ParseResult */
        ParseResult: {
            /** Description */
            description: string;
            /** Ingredient Groups */
            ingredient_groups: components["schemas"]["IngredientGroupOutput"][];
            /** Directions */
            directions: string;
            /** Notes */
            notes: string;
            /** Yield Amount */
            yield_amount: string | null;
            /** Yield Unit */
            yield_unit: string;
            /** Source Url */
            source_url: string;
        };
        /** ProfileInput */
        ProfileInput: {
            /** Display Name */
            display_name: string;
        };
        /** PublicUser */
        PublicUser: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** State */
            state: string;
            /** Trusted */
            trusted: boolean;
            /** Merged Into */
            merged_into?: string | null;
        };
        /** Recipe */
        Recipe: {
            /** Id */
            id: string;
            /** Revision */
            revision: number;
            /** Owner Id */
            owner_id: string | null;
            /** Author Name */
            author_name: string | null;
            /** Can Edit */
            can_edit: boolean;
            /** Enrichment Status */
            enrichment_status: string;
            /** Photos */
            photos?: {
                [key: string]: unknown;
            }[];
            /** Title */
            title: string;
            /** Source Text */
            source_text: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "text" | "structured";
            /** Description */
            description: string;
            /** Ingredient Groups */
            ingredient_groups: components["schemas"]["IngredientGroupOutput"][];
            /** Directions */
            directions: string;
            /** Notes */
            notes: string;
            /** Tags */
            tags: string[];
            /** Yield Amount */
            yield_amount: string | null;
            /** Yield Unit */
            yield_unit: string;
            /** Source Url */
            source_url: string;
            /** Modifications */
            modifications: string;
            /**
             * Total Views
             * @default 0
             */
            total_views: number;
            /**
             * Unique Viewers
             * @default 0
             */
            unique_viewers: number;
        };
        /** RecipeDraft */
        RecipeDraft: {
            /** Title */
            title: string;
            /**
             * Source Text
             * @default
             */
            source_text: string;
            /**
             * Mode
             * @default text
             * @enum {string}
             */
            mode: "text" | "structured";
            /**
             * Description
             * @default
             */
            description: string;
            /** Ingredient Groups */
            ingredient_groups?: components["schemas"]["IngredientGroup"][];
            /**
             * Directions
             * @default
             */
            directions: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Tags */
            tags?: string[];
            /** Yield Amount */
            yield_amount?: string | null;
            /**
             * Yield Unit
             * @default
             */
            yield_unit: string;
            /**
             * Source Url
             * @default
             */
            source_url: string;
            /**
             * Modifications
             * @default
             */
            modifications: string;
        };
        /** RecipeListResponse */
        RecipeListResponse: {
            /** Items */
            items: components["schemas"]["RecipeSummary"][];
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Total */
            total: number;
            /** Has More */
            has_more: boolean;
            /** Errors */
            errors: string[];
            /** Groups */
            groups: components["schemas"]["RecipeSummaryGroup"][];
            /** Popular */
            popular?: components["schemas"]["RecipeSummary"][];
        };
        /** RecipeLookupRequest */
        RecipeLookupRequest: {
            /** Ids */
            ids: string[];
            /**
             * Q
             * @default
             */
            q: string;
            /** Tags */
            tags?: string[];
        };
        /** RecipeLookupResponse */
        RecipeLookupResponse: {
            /** Items */
            items: components["schemas"]["RecipeSummary"][];
            /** Unavailable Ids */
            unavailable_ids: string[];
        };
        /** RecipeSummary */
        RecipeSummary: {
            /** Thumbnail Photo Id */
            thumbnail_photo_id?: string | null;
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Tags */
            tags: string[];
            /** Owner Id */
            owner_id: string | null;
            /** Author Name */
            author_name: string | null;
            /**
             * Total Views
             * @default 0
             */
            total_views: number;
            /**
             * Unique Viewers
             * @default 0
             */
            unique_viewers: number;
            /** Search Score */
            search_score?: number | null;
        };
        /** RecipeSummaryGroup */
        RecipeSummaryGroup: {
            /** Name */
            name: string;
            /** Items */
            items: components["schemas"]["RecipeSummary"][];
        };
        /** RecipeUpdate */
        RecipeUpdate: {
            /** Title */
            title: string;
            /**
             * Source Text
             * @default
             */
            source_text: string;
            /**
             * Mode
             * @default text
             * @enum {string}
             */
            mode: "text" | "structured";
            /**
             * Description
             * @default
             */
            description: string;
            /** Ingredient Groups */
            ingredient_groups?: components["schemas"]["IngredientGroup"][];
            /**
             * Directions
             * @default
             */
            directions: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Tags */
            tags?: string[];
            /** Yield Amount */
            yield_amount?: string | null;
            /**
             * Yield Unit
             * @default
             */
            yield_unit: string;
            /**
             * Source Url
             * @default
             */
            source_url: string;
            /**
             * Modifications
             * @default
             */
            modifications: string;
            /** Expected Revision */
            expected_revision: number;
        };
        /** RecipeViewCounts */
        RecipeViewCounts: {
            /**
             * Total Views
             * @default 0
             */
            total_views: number;
            /**
             * Unique Viewers
             * @default 0
             */
            unique_viewers: number;
        };
        /** RestoreInput */
        RestoreInput: {
            /** Revision Id */
            revision_id: string;
            /** Expected Revision */
            expected_revision: number;
        };
        /** SessionResponse */
        SessionResponse: {
            user: components["schemas"]["PublicUser"] | null;
            /** Device Id */
            device_id: string | null;
            /** Admin */
            admin: boolean;
            /** Csrf Token */
            csrf_token: string;
        };
        /** SiteCopy */
        SiteCopy: {
            /** Site Title */
            site_title: string;
            /** Site Tagline */
            site_tagline: string;
            /** Home Title */
            home_title: string;
            /** Home Intro */
            home_intro: string;
            /** Footer Text */
            footer_text: string;
        };
        /** SiteSettings */
        SiteSettings: {
            /** Revision */
            revision: number;
            copy: components["schemas"]["SiteCopy"];
        };
        /** SiteSettingsUpdate */
        SiteSettingsUpdate: {
            /** Expected Revision */
            expected_revision: number;
            copy: components["schemas"]["SiteCopy"];
        };
        /** TagCatalog */
        TagCatalog: {
            /** Tags */
            tags: string[];
            /** Classifier Tags */
            classifier_tags: string[];
        };
        /** UserInput */
        UserInput: {
            /** Trusted */
            trusted?: boolean | null;
            /** State */
            state?: ("active" | "blocked") | null;
            /** Is Admin */
            is_admin?: true | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    session_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    create_identity_api_identity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_identity_api_identity_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    devices_api_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    revoke_device_api_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pairing_api_pairings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    request_pairing_api_pairings_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairingInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pairing_status_api_pairings__pairing_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pairing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_pairing_api_pairings__pairing_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pairing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_pairing_api_pairings__pairing_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pairing_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_recipes_api_recipes_lookup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeLookupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeLookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recipes_api_recipes_get: {
        parameters: {
            query?: {
                q?: string;
                owner_id?: string | null;
                offset?: number;
                limit?: number;
                tag?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recipe_api_recipes_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeDraft"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagCatalog"];
                };
            };
        };
    };
    get_recipe_api_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_recipe_api_recipes__recipe_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recipe_api_recipes__recipe_id__delete: {
        parameters: {
            query: {
                expected_revision: number;
            };
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recipe_view_api_recipes__recipe_id__views_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeViewCounts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_lines_api_ingredients_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientLinesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientLinesResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_api_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enrich_recipe_api_recipes__recipe_id__enrich_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_api_admin_users_get: {
        parameters: {
            query?: {
                q?: string;
                start?: number;
                limit?: number;
                eligible_owner?: boolean;
                eligible_merge?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUsersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_owner_api_admin_recipes__recipe_id__owner_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revisions_api_admin_recipes__recipe_id__revisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_api_admin_recipes__recipe_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_preview_api_admin_merge_preview_get: {
        parameters: {
            query: {
                source_id: string;
                target_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_preview_body_api_admin_merge_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergePreviewInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_api_admin_merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_events_api_admin_audit_get: {
        parameters: {
            query?: {
                start?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    photos_api_admin_photos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    moderate_photo_api_admin_photos__photo_id__moderate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    moderate_photo_api_admin_photos__photo_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_site_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteSettings"];
                };
            };
        };
    };
    update_settings_api_admin_site_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    photos_api_photos_get: {
        parameters: {
            query?: {
                recipe_id?: string | null;
                mine?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_photo_api_recipes__recipe_id__photos_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_photo_api_recipes__recipe_id__photos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    photo_image_api_photos__photo_id__image_get: {
        parameters: {
            query?: {
                thumbnail?: boolean;
            };
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_photo_api_photos__photo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
