import { test, expect, createProfile, mutate, session, source, origin } from './fixtures';

test('reading and bookmarks do not create an identity; legacy recipe links resolve', async ({page, context, second, recipe}) => {
  await second.page.goto(`/#/view/${encodeURIComponent(recipe.id)}`);
  await expect(second.page).toHaveURL(`${origin}/recipes/${encodeURIComponent(recipe.id)}`);
  await expect(second.page.getByRole('heading', {name: recipe.title})).toBeVisible();
  expect(await second.page.locator('.recipe-body').textContent()).toBe(source);
  await second.page.getByRole('button', {name: 'Save for later'}).click();
  expect((await session(second.context.request)).user).toBeNull();
  await second.page.goto('/profile');
  await expect(second.page.getByRole('heading', {name: 'A name for your contribution'})).toBeVisible();
  expect((await session(second.context.request)).device_id).toBeNull();
  expect((await session(context.request)).user).not.toBeNull();
});

test('publishes without signup and keeps exact text when organizing fails', async ({page, context}) => {
  await page.goto('/new');
  await page.getByRole('button', {name: 'Start a new recipe', exact: true}).click();
  await page.getByLabel('Recipe title').fill(`Text fallback ${crypto.randomUUID()}`);
  await page.getByLabel('Paste or write your recipe').fill(source);
  await page.getByRole('button', {name: 'Organize', exact: true}).click();
  await expect(page.getByRole('alert')).toContainText('Your text is safe');
  expect((await session(context.request)).user).toBeNull();
  await expect(page.getByLabel('Paste or write your recipe')).toHaveValue(source);
  await expect(page.getByRole('button', {name: 'Publish recipe'})).toBeDisabled();
  await page.getByLabel('Your display name').fill('Text-only cook');
  await page.getByLabel('Your display name').press('Enter');
  await expect(page.getByText('Name set. Review your recipe, then publish.')).toBeVisible();
  await page.getByRole('button', {name: 'Publish recipe'}).click();
  await expect(page).toHaveURL(/\/recipes\//);
  expect(await page.locator('.recipe-body').textContent()).toBe(source);
  const recipe = await (await context.request.get(`/api${new URL(page.url()).pathname}`)).json();
  expect(recipe.mode).toBe('text');
  expect(recipe.source_text).toBe(source);
  const deleted = await mutate(context.request, `/recipes/${encodeURIComponent(recipe.id)}?expected_revision=${recipe.revision}`, undefined, 'DELETE');
  expect(deleted.status(), await deleted.text()).toBe(204);
});

test('two browsers enforce owner edits, deletes, and server-filtered My recipes', async ({page, context, second, recipe, owner}) => {
  await createProfile(second.context.request, 'Other owner');
  await second.page.goto(`/recipes/${encodeURIComponent(recipe.id)}/edit`);
  await expect(second.page.getByText('You can read this recipe, but only its owner or an administrator can edit it. Your local draft has been kept.')).toBeVisible();
  const path = `/recipes/${encodeURIComponent(recipe.id)}`;
  expect([403, 404]).toContain((await mutate(second.context.request, path, {title: 'Hijacked', mode: 'text', source_text: 'Changed', expected_revision: recipe.revision}, 'PUT')).status());
  expect([403, 404]).toContain((await mutate(second.context.request, `${path}?expected_revision=${recipe.revision}`, undefined, 'DELETE')).status());
  const other = await session(second.context.request);
  const filtered = await (await second.context.request.get(`/api/recipes?owner_id=${encodeURIComponent(other.user!.id)}`)).json();
  expect(filtered.items.every((item: {owner_id: string}) => item.owner_id === other.user!.id)).toBe(true);
  await page.goto('/profile');
  await page.getByText('Devices', {exact: true}).click();
  await expect(page.getByText('(this device)', {exact: false})).toBeVisible();
  await page.getByRole('button', {name: 'My recipes', exact: true}).click();
  await expect(page.getByRole('link', {name: recipe.title})).toBeVisible();
  expect((await (await context.request.get(`/api${path}`)).json()).owner_id).toBe(owner.user!.id);
});

test('pairing requires source approval and explicit destination switch; admin permission follows the profile', async ({page, context, owner, second, adminPermission}) => {
  await adminPermission(owner.user!.id, true);
  await createProfile(second.context.request, 'Destination cook');
  await page.goto('/profile');
  await page.getByText('Devices', {exact: true}).click();
  await page.getByRole('button', {name: 'Create pairing code'}).click();
  const code = await page.locator('.pair-code').textContent();
  await second.page.goto('/profile');
  await second.page.getByText('Connect an existing profile', {exact: true}).click();
  await second.page.getByLabel('Pairing code', {exact: true}).fill(code!);
  await second.page.getByRole('button', {name: 'Request connection'}).click();
  await expect(second.page.getByText('Status: requested', {exact: true})).toBeVisible();
  expect((await session(second.context.request)).user!.id).not.toBe(owner.user!.id);
  expect((await session(second.context.request)).admin).toBe(false);
  expect((await second.context.request.get('/api/admin/photos')).status()).toBe(403);
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', {name: 'Confirm this device request'}).click();
  const complete = second.page.getByRole('button', {name: 'Complete connection'});
  await expect(complete).toBeDisabled();
  await second.page.getByLabel('I want to switch this browser to this profile').check();
  await complete.click();
  await expect(second.page.getByText('This device is connected and now uses the selected profile’s permissions.')).toBeVisible();
  const destination = await session(second.context.request);
  expect(destination.user!.id).toBe(owner.user!.id);
  expect(destination.admin).toBe(true);
  expect((await second.context.request.get('/api/admin/photos')).status()).toBe(200);
  await adminPermission(owner.user!.id, false);
  for (const api of [context.request, second.context.request]) {
    expect((await session(api)).admin).toBe(false);
    expect((await api.get('/api/admin/photos')).status()).toBe(403);
  }
  expect((await (await context.request.get('/api/devices')).json()).devices.filter((device: {revoked_at: string | null}) => !device.revoked_at)).toHaveLength(2);
});

test('admin sees raw pending photos and moderates the actual submission', async ({page, context, second, recipe, adminPermission}) => {
  await page.goto(`/recipes/${encodeURIComponent(recipe.id)}`);
  await expect(page.getByRole('heading', {name: 'Photos', exact: true})).toBeVisible();
  const png = await page.evaluate(() => {const canvas = document.createElement('canvas'); canvas.width = 64; canvas.height = 64; const paint = canvas.getContext('2d')!; paint.fillStyle = '#c63'; paint.fillRect(0, 0, 64, 64); return canvas.toDataURL('image/png').split(',')[1];});
  const note = [`Dinner ${recipe.id}`, 'Substituted oat milk for cream and added smoked paprika.', 'x'.repeat(1050), 'The sauce stayed silky.\\n<script>window.photoNoteExecuted = true</script> remained plain text.'].join('\\n\\n');
  await page.getByLabel('Add a photo', {exact: true}).setInputFiles({name: 'dinner.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64')});
  await expect(page.getByText('Ready to upload.', {exact: true})).toBeVisible();
  await page.getByLabel('Photo note (optional)').fill(note);
  const requestedAt = new Date();
  await page.getByRole('button', {name: /Submit photo/}).click();
  await expect(page.getByText('Private submission: pending')).toBeVisible();
  const completedAt = new Date();
  await expect(page.locator('figure').filter({hasText: `Dinner ${recipe.id}`}).locator('.prose')).toHaveText(note);
  expect(await page.evaluate(() => (window as Window & {photoNoteExecuted?: boolean}).photoNoteExecuted)).toBeUndefined();
  const submissions = await (await context.request.get(`/api/photos?recipe_id=${encodeURIComponent(recipe.id)}&mine=true`)).json();
  expect(submissions.items).toHaveLength(1);
  const submitted = submissions.items[0];
  expect(submitted.status).toBe('pending');
  expect(submitted.caption).toBe(note);
  expect(submitted.created_at).toMatch(/(?:Z|\+00:00)$/);
  expect(new Date(submitted.created_at).getTime()).toBeGreaterThanOrEqual(requestedAt.getTime());
  expect(new Date(submitted.created_at).getTime()).toBeLessThanOrEqual(completedAt.getTime());
  const imagePath = `/api/photos/${encodeURIComponent(submitted.id)}/image`;
  await page.reload();
  const pendingPhoto = page.locator('figure').filter({hasText: `Dinner ${recipe.id}`});
  await expect(pendingPhoto.locator('.prose')).toHaveText(note);
  await expect(pendingPhoto.getByText('Uploaded', {exact: false})).toBeVisible();
  await second.page.goto('/admin');
  await expect(second.page.getByText('Your current profile does not have admin access.')).toBeVisible();
  expect((await session(second.context.request)).user).toBeNull();
  expect((await second.context.request.get(imagePath)).status()).toBe(404);
  const moderator = await createProfile(second.context.request, 'Photo moderator');
  expect((await second.context.request.get('/api/admin/photos')).status()).toBe(403);
  expect((await second.context.request.get(imagePath)).status()).toBe(404);
  expect((await (await second.context.request.get(`/api/photos?recipe_id=${encodeURIComponent(recipe.id)}`)).json()).items).toEqual([]);
  expect((await mutate(second.context.request, `/admin/photos/${encodeURIComponent(submitted.id)}/moderate`, {state: 'approved'})).status()).toBe(403);
  await adminPermission(moderator.user!.id, true);
  await second.page.reload();
  const image = await second.context.request.get(imagePath);
  expect(image.status()).toBe(200);
  expect(image.headers()['content-type']).toBe('image/jpeg');
  expect(image.headers()['cache-control']).toBe('private, no-store');
  const raw = await (await second.context.request.get('/api/admin/photos')).json();
  expect(raw.photos).toEqual(expect.arrayContaining([expect.objectContaining({id: submitted.id, status: 'pending', caption: note, created_at: submitted.created_at})]));
  const photo = second.page.locator('figure').filter({hasText: `Dinner ${recipe.id}`});
  await expect(photo).toContainText('pending');
  await expect(photo.locator('.prose')).toHaveText(note);
  await expect(photo.getByText('Uploaded', {exact: false})).toBeVisible();
  await photo.getByRole('button', {name: 'Approve', exact: true}).click();
  await expect(photo).toContainText('approved');
  await page.reload();
  const publishedPhoto = page.locator('figure').filter({hasText: `Dinner ${recipe.id}`});
  await expect(publishedPhoto).toBeVisible();
  await expect(publishedPhoto.locator('.prose')).toHaveText(note);
  await expect(publishedPhoto.getByText('Uploaded', {exact: false})).toBeVisible();
  await expect(publishedPhoto.getByText(/Private submission:/)).toHaveCount(0);
  expect((await (await context.request.get(`/api/photos?recipe_id=${encodeURIComponent(recipe.id)}&mine=true`)).json()).items)
    .toEqual(expect.arrayContaining([expect.objectContaining({id: submitted.id, status: 'approved', caption: note, created_at: submitted.created_at})]));
  expect((await session(second.context.request)).user!.id).toBe(moderator.user!.id);
  await adminPermission(moderator.user!.id, false);
  expect((await session(second.context.request)).admin).toBe(false);
  expect((await second.context.request.get('/api/admin/photos')).status()).toBe(403);
  expect((await mutate(second.context.request, `/admin/photos/${encodeURIComponent(submitted.id)}/moderate`, {state: 'pending'})).status()).toBe(403);
  expect((await second.context.request.get(imagePath)).status()).toBe(200);
  expect((await (await second.context.request.get(`/api/photos?recipe_id=${encodeURIComponent(recipe.id)}`)).json()).items).toEqual(expect.arrayContaining([expect.objectContaining({id: submitted.id, status: 'approved'})]));
});

test('drag and drop prepares a draft and discard permits selecting the same file', async ({page, context, recipe}) => {
  await page.goto(`/recipes/${encodeURIComponent(recipe.id)}`);
  const png = await page.evaluate(() => {const canvas = document.createElement('canvas'); canvas.width = 48; canvas.height = 48; const paint = canvas.getContext('2d')!; paint.fillStyle = '#486'; paint.fillRect(0, 0, 48, 48); return canvas.toDataURL('image/png').split(',')[1];});
  const drop = async () => page.locator('.dropper').evaluate((element, value) => {
    const bytes = Uint8Array.from(atob(value), character => character.charCodeAt(0));
    const transfer = new DataTransfer();
    transfer.items.add(new File([bytes], 'dropped.png', {type: 'image/png'}));
    element.dispatchEvent(new DragEvent('drop', {bubbles: true, cancelable: true, dataTransfer: transfer}));
  }, png);

  await drop();
  const noteInput = page.getByLabel('Photo note (optional)');
  await expect(noteInput).toBeVisible();
  await expect(page.locator('.dropper')).toHaveCount(0);
  expect((await (await context.request.get(`/api/photos?recipe_id=${encodeURIComponent(recipe.id)}&mine=true`)).json()).items).toEqual([]);
  const note = 'Dropped this photo.\\n\\nUsed less salt and the crust stayed crisp.';
  await noteInput.fill(note);
  await page.getByRole('button', {name: 'Submit photo'}).click();
  await expect(page.getByText('Photo submitted.')).toBeVisible();
  const saved = await (await context.request.get(`/api/photos?recipe_id=${encodeURIComponent(recipe.id)}&mine=true`)).json();
  expect(saved.items).toEqual([expect.objectContaining({caption: note})]);

  const input = page.getByLabel('Add a photo', {exact: true});
  const file = {name: 'dropped.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64')};
  await input.setInputFiles(file);
  await expect(page.getByLabel('Photo note (optional)')).toHaveValue('');
  await page.getByLabel('Photo note (optional)').fill('Discard me');
  await page.getByRole('button', {name: 'Discard photo'}).click();
  await expect(page.getByLabel('Add a photo', {exact: true})).toBeVisible();
  await page.getByLabel('Add a photo', {exact: true}).setInputFiles(file);
  await expect(page.getByLabel('Photo note (optional)')).toBeVisible();
  await expect(page.getByLabel('Photo note (optional)')).toHaveValue('');
});
