"""
Migration: 0001_initial
Generated: 2026-09-07T04:53:33.334074+00:00

Auto-generated migration file. Review before applying.
"""

from surreal_orm.migrations import Migration
import re
from surreal_orm.migrations.operations import (
    AddField,
    CreateTable,
    CreateIndex,
)


class AddField(AddField):
    """Reviewed correction: 3.2 requires TYPE object FLEXIBLE, not FLEXIBLE TYPE."""

    def forwards(self):
        sql = super().forwards()
        return re.sub(r"FLEXIBLE TYPE ([^; ]+)", r"TYPE \1 FLEXIBLE", sql)


migration = Migration(
    name="0001_initial",
    dependencies=[],
    operations=[
        CreateTable(name='users', table_type='normal'),
        AddField(table='users', name='created_at', field_type='datetime'),
        AddField(table='users', name='updated_at', field_type='datetime'),
        AddField(
            table='users',
            name='payload',
            field_type='object',
            flexible=True,
        ),
        AddField(
            table='users',
            name='display_name',
            field_type='string',
            default='Anonymous',
        ),
        AddField(
            table='users',
            name='state',
            field_type='string',
            default='active',
        ),
        AddField(
            table='users',
            name='photo_trust',
            field_type='bool',
            default=False,
        ),
        AddField(
            table='users',
            name='merged_into',
            field_type='record<users>',
            reference=True,
            on_delete='REJECT',
            nullable=True,
        ),
        CreateTable(name='devices', table_type='normal'),
        AddField(table='devices', name='created_at', field_type='datetime'),
        AddField(table='devices', name='updated_at', field_type='datetime'),
        AddField(
            table='devices',
            name='payload',
            field_type='object',
            flexible=True,
        ),
        AddField(
            table='devices',
            name='user_id',
            field_type='record<users>',
            reference=True,
            on_delete='REJECT',
            nullable=True,
        ),
        AddField(
            table='devices',
            name='secret_hash',
            field_type='string',
            default='',
        ),
        AddField(
            table='devices',
            name='label',
            field_type='string',
            nullable=True,
        ),
        AddField(
            table='devices',
            name='last_used_at',
            field_type='datetime',
            nullable=True,
        ),
        AddField(
            table='devices',
            name='expires_at',
            field_type='datetime',
            nullable=True,
        ),
        AddField(
            table='devices',
            name='revoked_at',
            field_type='datetime',
            nullable=True,
        ),
        CreateTable(name='pairings', table_type='normal'),
        AddField(table='pairings', name='created_at', field_type='datetime'),
        AddField(table='pairings', name='updated_at', field_type='datetime'),
        AddField(
            table='pairings',
            name='payload',
            field_type='object',
            flexible=True,
        ),
        AddField(
            table='pairings',
            name='source_user_id',
            field_type='record<users>',
            reference=True,
            on_delete='REJECT',
            nullable=True,
        ),
        AddField(
            table='pairings',
            name='source_device_id',
            field_type='record<devices>',
            reference=True,
            on_delete='REJECT',
            nullable=True,
        ),
        AddField(
            table='pairings',
            name='token_hash',
            field_type='string',
            default='',
        ),
        AddField(
            table='pairings',
            name='code_hash',
            field_type='string',
            default='',
        ),
        AddField(
            table='pairings',
            name='status',
            field_type='string',
            default='pending',
        ),
        AddField(
            table='pairings',
            name='attempts',
            field_type='int',
            default=0,
        ),
        AddField(
            table='pairings',
            name='expires_at',
            field_type='datetime',
            nullable=True,
        ),
        AddField(
            table='pairings',
            name='revision',
            field_type='int',
            default=1,
        ),
        CreateTable(name='admin_sessions', table_type='normal'),
        AddField(
            table='admin_sessions',
            name='created_at',
            field_type='datetime',
        ),
        AddField(
            table='admin_sessions',
            name='updated_at',
            field_type='datetime',
        ),
        AddField(
            table='admin_sessions',
            name='payload',
            field_type='object',
            flexible=True,
        ),
        AddField(
            table='admin_sessions',
            name='secret_hash',
            field_type='string',
            default='',
        ),
        AddField(
            table='admin_sessions',
            name='expires_at',
            field_type='datetime',
            nullable=True,
        ),
        AddField(
            table='admin_sessions',
            name='revoked_at',
            field_type='datetime',
            nullable=True,
        ),
        CreateTable(name='recipes', table_type='normal'),
        AddField(table='recipes', name='created_at', field_type='datetime'),
        AddField(table='recipes', name='updated_at', field_type='datetime'),
        AddField(
            table='recipes',
            name='payload',
            field_type='object',
            flexible=True,
        ),
        AddField(
            table='recipes',
            name='owner_id',
            field_type='record<users>',
            reference=True,
            on_delete='REJECT',
            nullable=True,
        ),
        AddField(
            table='recipes',
            name='title',
            field_type='string',
            default='',
        ),
        AddField(
            table='recipes',
            name='mode',
            field_type='string',
            default='source',
        ),
        AddField(
            table='recipes',
            name='status',
            field_type='string',
            default='draft',
        ),
        AddField(
            table='recipes',
            name='source_text',
            field_type='string',
            default='',
        ),
        AddField(
            table='recipes',
            name='instructions',
            field_type='string',
            default='',
        ),
        AddField(
            table='recipes',
            name='description',
            field_type='string',
            default='',
        ),
        AddField(
            table='recipes',
            name='ingredient_groups',
            field_type='array<object>',  # Reviewed: nested Pydantic models introspect as any.
            flexible=True,
        ),
        AddField(table='recipes', name='tags', field_type='array<string>'),
        AddField(
            table='recipes',
            name='servings',
            field_type='float',
            nullable=True,
        ),
        AddField(
            table='recipes',
            name='revision',
            field_type='int',
            default=1,
        ),
        AddField(
            table='recipes',
            name='deleted_at',
            field_type='datetime',
            nullable=True,
        ),
        CreateTable(name='revisions', table_type='normal'),
        AddField(table='revisions', name='created_at', field_type='datetime'),
        AddField(table='revisions', name='updated_at', field_type='datetime'),
        AddField(
            table='revisions',
            name='payload',
            field_type='object',
            flexible=True,
        ),
        AddField(
            table='revisions',
            name='recipe_id',
            field_type='record<recipes>',
            reference=True,
            on_delete='REJECT',
            nullable=True,
        ),
        AddField(
            table='revisions',
            name='actor_id',
            field_type='record<users>',
            reference=True,
            on_delete='REJECT',
            nullable=True,
        ),
        AddField(
            table='revisions',
            name='revision',
            field_type='int',
            default=1,
        ),
        AddField(
            table='revisions',
            name='reason',
            field_type='string',
            default='edit',
        ),
        AddField(
            table='revisions',
            name='content',
            field_type='object',
            flexible=True,
        ),
        CreateTable(name='photos', table_type='normal'),
        AddField(table='photos', name='created_at', field_type='datetime'),
        AddField(table='photos', name='updated_at', field_type='datetime'),
        AddField(
            table='photos',
            name='payload',
            field_type='object',
            flexible=True,
        ),
        AddField(
            table='photos',
            name='recipe_id',
            field_type='record<recipes>',
            reference=True,
            on_delete='REJECT',
            nullable=True,
        ),
        AddField(
            table='photos',
            name='uploader_id',
            field_type='record<users>',
            reference=True,
            on_delete='REJECT',
            nullable=True,
        ),
        AddField(
            table='photos',
            name='storage_key',
            field_type='string',
            default='',
        ),
        AddField(
            table='photos',
            name='thumbnail_key',
            field_type='string',
            default='',
        ),
        AddField(table='photos', name='width', field_type='int', default=0),
        AddField(table='photos', name='height', field_type='int', default=0),
        AddField(
            table='photos',
            name='size_bytes',
            field_type='int',
            default=0,
        ),
        AddField(
            table='photos',
            name='caption',
            field_type='string',
            default='',
        ),
        AddField(
            table='photos',
            name='status',
            field_type='string',
            default='pending',
        ),
        AddField(
            table='photos',
            name='moderation_reason',
            field_type='string',
            nullable=True,
        ),
        AddField(
            table='photos',
            name='moderated_at',
            field_type='datetime',
            nullable=True,
        ),
        CreateTable(name='jobs', table_type='normal'),
        AddField(table='jobs', name='created_at', field_type='datetime'),
        AddField(table='jobs', name='updated_at', field_type='datetime'),
        AddField(
            table='jobs',
            name='payload',
            field_type='object',
            flexible=True,
        ),
        AddField(
            table='jobs',
            name='recipe_id',
            field_type='record<recipes>',
            reference=True,
            on_delete='REJECT',
            nullable=True,
        ),
        AddField(
            table='jobs',
            name='kind',
            field_type='string',
            default='grams',
        ),
        AddField(
            table='jobs',
            name='input_revision',
            field_type='int',
            default=1,
        ),
        AddField(
            table='jobs',
            name='input_hash',
            field_type='string',
            default='',
        ),
        AddField(
            table='jobs',
            name='dedupe_key',
            field_type='string',
            nullable=True,
        ),
        AddField(
            table='jobs',
            name='state',
            field_type='string',
            default='pending',
        ),
        AddField(table='jobs', name='attempts', field_type='int', default=0),
        AddField(
            table='jobs',
            name='lease_until',
            field_type='datetime',
            nullable=True,
        ),
        AddField(table='jobs', name='available_at', field_type='datetime'),
        AddField(table='jobs', name='revision', field_type='int', default=1),
        CreateTable(name='audit', table_type='normal'),
        AddField(table='audit', name='created_at', field_type='datetime'),
        AddField(table='audit', name='updated_at', field_type='datetime'),
        AddField(
            table='audit',
            name='payload',
            field_type='object',
            flexible=True,
        ),
        AddField(
            table='audit',
            name='actor_id',
            field_type='record<users>',
            reference=True,
            on_delete='REJECT',
            nullable=True,
        ),
        AddField(
            table='audit',
            name='action',
            field_type='string',
            default='',
        ),
        AddField(
            table='audit',
            name='target',
            field_type='string',
            default='',
        ),
        CreateTable(name='usage', table_type='normal'),
        AddField(table='usage', name='created_at', field_type='datetime'),
        AddField(table='usage', name='updated_at', field_type='datetime'),
        AddField(
            table='usage',
            name='payload',
            field_type='object',
            flexible=True,
        ),
        AddField(
            table='usage',
            name='scope',
            field_type='string',
            default='',
        ),
        AddField(table='usage', name='kind', field_type='string', default=''),
        AddField(table='usage', name='count', field_type='int', default=0),
        AddField(
            table='usage',
            name='expires_at',
            field_type='datetime',
            nullable=True,
        ),
        AddField(table='usage', name='revision', field_type='int', default=1),
        # Reviewed operational indexes; unique dedupe keys are optional.
        CreateIndex(table='recipes', name='recipe_owner', fields=['owner_id']),
        CreateIndex(table='recipes', name='recipe_browse', fields=['status', 'deleted_at', 'updated_at']),
        CreateIndex(table='devices', name='device_user', fields=['user_id']),
        CreateIndex(table='photos', name='photo_recipe_status', fields=['recipe_id', 'status']),
        CreateIndex(table='jobs', name='job_claim', fields=['state', 'available_at']),
        CreateIndex(table='jobs', name='job_dedupe', fields=['dedupe_key'], unique=True),
        CreateIndex(table='revisions', name='recipe_revision', fields=['recipe_id', 'revision'], unique=True),
        CreateIndex(table='usage', name='usage_scope', fields=['scope', 'kind', 'expires_at']),
    ],
)
